# title: 'ğŸ‘¨â€ğŸ’» ğŸ“– ğŸš€ ğŸ”'
title: Suhaas Srinvas Gandham's CV
description: Android Applications Engineer - Lucid Motors | Masters CS Student - USC | Ex Senior Research Engineer at Hyundai Mobis | Major League Hacking (MLH) HackUPC Winner 2017
theme: jekyll-theme-slate
